host: Mac.localdomain
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job stats:
job                 count
----------------  -------
all                     1
model_evaluation        2
model_tranining         2
total                   5

Select jobs to execute...
Execute 2 jobs...

[Sat Mar 22 12:29:14 2025]
localrule model_tranining:
    input: data/transformed_data/transformed_train_X.csv, data/transformed_data/label_encoded_train_y.csv
    output: models/RandomForest.pkl
    jobid: 2
    benchmark: benchmarks/model_evaluation_RandomForest.txt
    reason: Missing output files: models/RandomForest.pkl
    wildcards: model=RandomForest
    resources: tmpdir=/var/folders/vw/j0gj7skx0qdbp446rdwrjyz80000gn/T

[Sat Mar 22 12:29:14 2025]
localrule model_tranining:
    input: data/transformed_data/transformed_train_X.csv, data/transformed_data/label_encoded_train_y.csv
    output: models/MulticlassLogisticsRegression.pkl
    jobid: 6
    benchmark: benchmarks/model_evaluation_MulticlassLogisticsRegression.txt
    reason: Missing output files: models/MulticlassLogisticsRegression.pkl
    wildcards: model=MulticlassLogisticsRegression
    resources: tmpdir=/var/folders/vw/j0gj7skx0qdbp446rdwrjyz80000gn/T

RuleException:
CalledProcessError in file /Users/eshita-pc/Documents/Second_year/programming 6/Snakemake/main.smk, line 54:
Command 'set -euo pipefail;  /Users/eshita-pc/miniconda3/envs/paint/bin/python3.12 '/Users/eshita-pc/Documents/Second_year/programming 6/Snakemake/.snakemake/scripts/tmp0iisez9e.RandomForest.py'' returned non-zero exit status 1.
[Sat Mar 22 12:29:16 2025]
Error in rule model_tranining:
    jobid: 2
    input: data/transformed_data/transformed_train_X.csv, data/transformed_data/label_encoded_train_y.csv
    output: models/RandomForest.pkl

RuleException:
CalledProcessError in file /Users/eshita-pc/Documents/Second_year/programming 6/Snakemake/main.smk, line 54:
Command 'set -euo pipefail;  /Users/eshita-pc/miniconda3/envs/paint/bin/python3.12 '/Users/eshita-pc/Documents/Second_year/programming 6/Snakemake/.snakemake/scripts/tmpo8klktqo.MulticlassLogisticsRegression.py'' returned non-zero exit status 1.
[Sat Mar 22 12:29:18 2025]
Error in rule model_tranining:
    jobid: 6
    input: data/transformed_data/transformed_train_X.csv, data/transformed_data/label_encoded_train_y.csv
    output: models/MulticlassLogisticsRegression.pkl

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2025-03-22T122914.507805.snakemake.log
WorkflowError:
At least one job did not complete successfully.
